name: Publish to RedGuides

on:
  push:
    branches: [ "main" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: "${{ github.ref }}"

      - name: Build zip file
        run: git archive --format=zip -o "${{ github.event.repository.name }}_${{ github.ref_name }}.zip" HEAD

      - name: Publish to RedGuides
        uses: RedGuides/redguides-publish@v1
        env:
          REDGUIDES_API_KEY: ${{ secrets.REDGUIDES_API_KEY }}
        with:
          resource_id: "3012"
          version: "${{ github.ref_name }}"
          file: "${{ github.event.repository.name }}_${{ github.ref_name }}.zip"
          domain: "https://raw.githubusercontent.com/${{ github.repository }}/${{ github.event.repository.default_branch }}/"
